
[dungeon-qol]

	[dungeon-qol.alerts]
		rag_axe_alert = true

	[dungeon-qol.refill]
		refill_boom = true

	[dungeon-qol.timers]
		m3_timer = false

	[dungeon-qol.render]
		render_sheeps = true

[dev]

	[dev.entity]
		mob_esp = false
		print_entitys = false

["m7/f7"]

	["m7/f7".m7_p5]
		all_leaped = false

	["m7/f7".storm]
		pad_timer = false

[qol]

	[qol.rewarp]
		rewarp = false
		rewarp_on_coords = false
		rewarp_to = "warp mines"
		rewarp_monolyth = false
		rewarp_coords = "0,0,0"

	[qol.kicked]
		auto_rejoin_on_kick = true

