import config from "./config"

import "./Features/vexo/Dungeon-QOL/ffrz"
import "./Features/vexo/Dungeon-QOL/m7padTimer"
import "./Features/vexo/Dungeon-QOL/sbTNT"
import "./Features/vexo/Dev/printEntity"
import "./Features/vexo/Dev/starredMobEsp"
import "./Features/vexo/Dungeon-QOL/RagAxeNow"
import "./Features/vexo/Dungeon-QOL/allLeapedP5"
import "./Features/vexo/QOL/rejoin"
import "./Features/vexo/Dungeon-QOL/StopMageSheepRendering"

import { GUICommand } from "./Features/gui"
import { RewarpCommand } from "./Features/vexo/QOL/rewarp"
import { TYFRCommand } from "./Features/vexo/Dungeon-QOL/tyfr"
import { SuckTrapCommand } from "./Features/vexo/Dungeon-QOL/SuckTrap"